import flask

app = flask.Flask(__name__)


@app.route("/player", methods=["POST"])
def index():
    return """
{
    "additional_rating": 7,
    "charts": {
        "dx": [
            {
                "achievements": 99.1868,
                "ds": 13.3,
                "dxScore": 1394,
                "fc": "",
                "fs": "sync",
                "level": "13",
                "level_index": 4,
                "level_label": "Re:MASTER",
                "ra": 274,
                "rate": "ss",
                "song_id": 11558,
                "title": "\u795e\u3063\u307d\u3044\u306a",
                "type": "DX"
            },
            {
                "achievements": 99.3157,
                "ds": 12.8,
                "dxScore": 2253,
                "fc": "",
                "fs": "sync",
                "level": "12+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 264,
                "rate": "ss",
                "song_id": 11526,
                "title": "\u30c8\u30ce\u30b5\u30de\u30d3\u30fc\u30e0",
                "type": "DX"
            },
            {
                "achievements": 99.6632,
                "ds": 11.7,
                "dxScore": 1223,
                "fc": "fc",
                "fs": "fs",
                "level": "11+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 246,
                "rate": "ssp",
                "song_id": 11558,
                "title": "\u795e\u3063\u307d\u3044\u306a",
                "type": "DX"
            },
            {
                "achievements": 99.376,
                "ds": 11.5,
                "dxScore": 1492,
                "fc": "",
                "fs": "sync",
                "level": "11",
                "level_index": 3,
                "level_label": "Master",
                "ra": 237,
                "rate": "ss",
                "song_id": 11562,
                "title": "\u30ed\u30a6\u30ef\u30fc",
                "type": "DX"
            },
            {
                "achievements": 97.7513,
                "ds": 12.0,
                "dxScore": 1036,
                "fc": "",
                "fs": "sync",
                "level": "12",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 234,
                "rate": "s",
                "song_id": 11527,
                "title": "enchanted wanderer",
                "type": "DX"
            },
            {
                "achievements": 95.1271,
                "ds": 13.5,
                "dxScore": 1796,
                "fc": "",
                "fs": "sync",
                "level": "13",
                "level_index": 4,
                "level_label": "Re:MASTER",
                "ra": 215,
                "rate": "aaa",
                "song_id": 11562,
                "title": "\u30ed\u30a6\u30ef\u30fc",
                "type": "DX"
            },
            {
                "achievements": 100.6097,
                "ds": 9.5,
                "dxScore": 1005,
                "fc": "fcp",
                "fs": "sync",
                "level": "9",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 213,
                "rate": "sssp",
                "song_id": 11559,
                "title": "\u9b54\u6cd5\u5c11\u5973\u3068\u30c1\u30e7\u30b3\u30ec\u3090\u30c8",
                "type": "DX"
            }
        ],
        "sd": [
            {
                "achievements": 100.4022,
                "ds": 13.4,
                "dxScore": 1976,
                "fc": "fc",
                "fs": "",
                "level": "13",
                "level_index": 3,
                "level_label": "Master",
                "ra": 290,
                "rate": "sss",
                "song_id": 417,
                "title": "\u30a6\u30df\u30e6\u30ea\u6d77\u5e95\u8b5a",
                "type": "SD"
            },
            {
                "achievements": 100.6659,
                "ds": 12.8,
                "dxScore": 1865,
                "fc": "fc",
                "fs": "",
                "level": "12+",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 288,
                "rate": "sssp",
                "song_id": 772,
                "title": "FREEDOM DiVE (tpz Overcute Remix)",
                "type": "SD"
            },
            {
                "achievements": 100.0716,
                "ds": 13.2,
                "dxScore": 1974,
                "fc": "",
                "fs": "",
                "level": "13",
                "level_index": 4,
                "level_label": "Re:MASTER",
                "ra": 285,
                "rate": "sss",
                "song_id": 792,
                "title": "\u30d2\u30d0\u30ca",
                "type": "SD"
            },
            {
                "achievements": 99.8066,
                "ds": 13.5,
                "dxScore": 2265,
                "fc": "",
                "fs": "",
                "level": "13",
                "level_index": 3,
                "level_label": "Master",
                "ra": 284,
                "rate": "ssp",
                "song_id": 11396,
                "title": "\u30c6\u30ea\u30c8\u30ea\u30fc\u30d0\u30c8\u30eb",
                "type": "DX"
            },
            {
                "achievements": 100.5606,
                "ds": 12.6,
                "dxScore": 1719,
                "fc": "fc",
                "fs": "",
                "level": "12",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 283,
                "rate": "sssp",
                "song_id": 711,
                "title": "\u62dd\u5553\u30c9\u30c3\u30da\u30eb\u30b2\u30f3\u30ac\u30fc",
                "type": "SD"
            },
            {
                "achievements": 99.1612,
                "ds": 13.7,
                "dxScore": 2125,
                "fc": "",
                "fs": "",
                "level": "13+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 282,
                "rate": "ss",
                "song_id": 11347,
                "title": "\u6ce5\u306e\u5206\u969b\u3067\u79c1\u3060\u3051\u306e\u5927\u5207\u3092\u596a\u304a\u3046\u3060\u306a\u3093\u3066",
                "type": "DX"
            },
            {
                "achievements": 99.3065,
                "ds": 13.5,
                "dxScore": 2106,
                "fc": "",
                "fs": "",
                "level": "13",
                "level_index": 3,
                "level_label": "Master",
                "ra": 278,
                "rate": "ss",
                "song_id": 11568,
                "title": "INTERNET OVERDOSE",
                "type": "DX"
            },
            {
                "achievements": 100.0373,
                "ds": 12.9,
                "dxScore": 1661,
                "fc": "fc",
                "fs": "",
                "level": "12+",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 278,
                "rate": "sss",
                "song_id": 11389,
                "title": "Sage",
                "type": "DX"
            },
            {
                "achievements": 100.0714,
                "ds": 12.8,
                "dxScore": 1486,
                "fc": "",
                "fs": "",
                "level": "12+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 276,
                "rate": "sss",
                "song_id": 11572,
                "title": "tape/stop/night",
                "type": "DX"
            },
            {
                "achievements": 100.0584,
                "ds": 12.8,
                "dxScore": 1945,
                "fc": "fc",
                "fs": "fs",
                "level": "12+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 276,
                "rate": "sss",
                "song_id": 647,
                "title": "\u30a8\u30a4\u30ea\u30a2\u30f3\u30a8\u30a4\u30ea\u30a2\u30f3",
                "type": "SD"
            },
            {
                "achievements": 100.2633,
                "ds": 12.7,
                "dxScore": 1674,
                "fc": "",
                "fs": "",
                "level": "12+",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 275,
                "rate": "sss",
                "song_id": 11302,
                "title": "BLACK SWAN",
                "type": "DX"
            },
            {
                "achievements": 100.2547,
                "ds": 12.7,
                "dxScore": 2652,
                "fc": "",
                "fs": "",
                "level": "12+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 275,
                "rate": "sss",
                "song_id": 11007,
                "title": "\u8d85\u5e38\u30de\u30a4\u30de\u30a4\u30f3",
                "type": "DX"
            },
            {
                "achievements": 100.1303,
                "ds": 12.7,
                "dxScore": 2001,
                "fc": "fcp",
                "fs": "",
                "level": "12+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 274,
                "rate": "sss",
                "song_id": 11268,
                "title": "\u732b\u732b\u7684\u5b87\u5b99\u8ad6",
                "type": "DX"
            },
            {
                "achievements": 99.2303,
                "ds": 13.3,
                "dxScore": 1855,
                "fc": "",
                "fs": "",
                "level": "13",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 274,
                "rate": "ss",
                "song_id": 566,
                "title": "\u5929\u706b\u660e\u547d",
                "type": "SD"
            },
            {
                "achievements": 100.0186,
                "ds": 12.7,
                "dxScore": 1988,
                "fc": "",
                "fs": "",
                "level": "12+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 274,
                "rate": "sss",
                "song_id": 11095,
                "title": "\u7d61\u3081\u30c8\u30ea\u30c3\u30af\u5229\u5df1\u30e9\u30a4\u30b6\u30fc",
                "type": "DX"
            },
            {
                "achievements": 100.3914,
                "ds": 12.6,
                "dxScore": 1190,
                "fc": "fc",
                "fs": "fsp",
                "level": "12",
                "level_index": 3,
                "level_label": "Master",
                "ra": 273,
                "rate": "sss",
                "song_id": 10536,
                "title": "\u6708\u306b\u53e2\u96f2\u83ef\u306b\u98a8",
                "type": "DX"
            },
            {
                "achievements": 98.1732,
                "ds": 13.7,
                "dxScore": 1747,
                "fc": "",
                "fs": "",
                "level": "13+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 273,
                "rate": "sp",
                "song_id": 11447,
                "title": "\u30a8\u30b4\u30ed\u30c3\u30af",
                "type": "DX"
            },
            {
                "achievements": 98.3296,
                "ds": 13.7,
                "dxScore": 2383,
                "fc": "",
                "fs": "",
                "level": "13+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 273,
                "rate": "sp",
                "song_id": 11296,
                "title": "\u3068\u3073\u3060\u305b\uff01TO THE COSMIC!!",
                "type": "DX"
            },
            {
                "achievements": 98.1574,
                "ds": 13.7,
                "dxScore": 1943,
                "fc": "",
                "fs": "",
                "level": "13+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 272,
                "rate": "sp",
                "song_id": 11383,
                "title": "Irresistible",
                "type": "DX"
            },
            {
                "achievements": 99.3571,
                "ds": 13.2,
                "dxScore": 1868,
                "fc": "",
                "fs": "",
                "level": "13",
                "level_index": 4,
                "level_label": "Re:MASTER",
                "ra": 272,
                "rate": "ss",
                "song_id": 731,
                "title": "\u5984\u60f3\u611f\u50b7\u4ee3\u511f\u9023\u76df",
                "type": "SD"
            },
            {
                "achievements": 99.287,
                "ds": 13.2,
                "dxScore": 1602,
                "fc": "",
                "fs": "",
                "level": "13",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 272,
                "rate": "ss",
                "song_id": 488,
                "title": "Lividi",
                "type": "SD"
            },
            {
                "achievements": 100.4239,
                "ds": 12.5,
                "dxScore": 2049,
                "fc": "",
                "fs": "",
                "level": "12",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 271,
                "rate": "sss",
                "song_id": 11576,
                "title": "Cthugha",
                "type": "DX"
            },
            {
                "achievements": 100.3936,
                "ds": 12.5,
                "dxScore": 1414,
                "fc": "fc",
                "fs": "",
                "level": "12",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 271,
                "rate": "sss",
                "song_id": 672,
                "title": "MilK",
                "type": "SD"
            },
            {
                "achievements": 99.7378,
                "ds": 12.9,
                "dxScore": 1766,
                "fc": "",
                "fs": "",
                "level": "12+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 271,
                "rate": "ssp",
                "song_id": 10191,
                "title": "\u8133\u6f3f\u70b8\u88c2\u30ac\u30fc\u30eb",
                "type": "DX"
            },
            {
                "achievements": 99.8627,
                "ds": 12.9,
                "dxScore": 2130,
                "fc": "",
                "fs": "",
                "level": "12+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 271,
                "rate": "ssp",
                "song_id": 11439,
                "title": "\u30b8\u30e3\u30f3\u30ad\u30fc\u30ca\u30a4\u30c8\u30bf\u30a6\u30f3\u30aa\u30fc\u30b1\u30b9\u30c8\u30e9",
                "type": "DX"
            },
            {
                "achievements": 98.918,
                "ds": 13.5,
                "dxScore": 1819,
                "fc": "",
                "fs": "",
                "level": "13",
                "level_index": 3,
                "level_label": "Master",
                "ra": 271,
                "rate": "sp",
                "song_id": 472,
                "title": "\u30a2\u30fc\u30b8\u30a7\u30f3\u30c8\u30b7\u30f3\u30e1\u30c8\u30ea\u30fc",
                "type": "SD"
            },
            {
                "achievements": 100.1577,
                "ds": 12.5,
                "dxScore": 1968,
                "fc": "",
                "fs": "",
                "level": "12",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 270,
                "rate": "sss",
                "song_id": 11296,
                "title": "\u3068\u3073\u3060\u305b\uff01TO THE COSMIC!!",
                "type": "DX"
            },
            {
                "achievements": 100.2192,
                "ds": 12.5,
                "dxScore": 1721,
                "fc": "fc",
                "fs": "fsp",
                "level": "12",
                "level_index": 3,
                "level_label": "Master",
                "ra": 270,
                "rate": "sss",
                "song_id": 11115,
                "title": "\u3060\u304b\u3089\u50d5\u306f\u97f3\u697d\u3092\u8f9e\u3081\u305f",
                "type": "DX"
            },
            {
                "achievements": 100.5874,
                "ds": 12.0,
                "dxScore": 1717,
                "fc": "",
                "fs": "",
                "level": "12",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 270,
                "rate": "sssp",
                "song_id": 11575,
                "title": "\u50d5\u306e\u548c\u98a8\u672c\u5f53\u4e0a\u624b",
                "type": "DX"
            },
            {
                "achievements": 100.6907,
                "ds": 12.0,
                "dxScore": 1312,
                "fc": "fcp",
                "fs": "",
                "level": "12",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 270,
                "rate": "sssp",
                "song_id": 11385,
                "title": "N3V3R G3T OV3R",
                "type": "DX"
            },
            {
                "achievements": 99.4165,
                "ds": 13.1,
                "dxScore": 1720,
                "fc": "",
                "fs": "",
                "level": "13",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 270,
                "rate": "ss",
                "song_id": 664,
                "title": "Moon of Noon",
                "type": "SD"
            },
            {
                "achievements": 100.6269,
                "ds": 12.0,
                "dxScore": 1936,
                "fc": "fc",
                "fs": "",
                "level": "12",
                "level_index": 3,
                "level_label": "Master",
                "ra": 270,
                "rate": "sssp",
                "song_id": 11069,
                "title": "\u592a\u967d\u7cfb\u30c7\u30b9\u30b3",
                "type": "DX"
            },
            {
                "achievements": 100.2315,
                "ds": 12.5,
                "dxScore": 1495,
                "fc": "fc",
                "fs": "fsp",
                "level": "12",
                "level_index": 2,
                "level_label": "Expert",
                "ra": 270,
                "rate": "sss",
                "song_id": 705,
                "title": "Mare Maris",
                "type": "SD"
            },
            {
                "achievements": 97.8387,
                "ds": 13.8,
                "dxScore": 2201,
                "fc": "",
                "fs": "",
                "level": "13+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 270,
                "rate": "s",
                "song_id": 11566,
                "title": "Knight Rider",
                "type": "DX"
            },
            {
                "achievements": 97.8982,
                "ds": 13.8,
                "dxScore": 1714,
                "fc": "",
                "fs": "",
                "level": "13+",
                "level_index": 3,
                "level_label": "Master",
                "ra": 270,
                "rate": "s",
                "song_id": 841,
                "title": "\u7d42\u70b9",
                "type": "SD"
            }
        ]
    },
    "nickname": "a1exlin",
    "plate": "",
    "rating": 11295,
    "user_general_data": null,
    "username": "a1exlin"
}"""


if __name__ == "__main__":
    app.run(debug=True)
